### ISSUE TITLE
Consider extending the GridSearchCV class in order to include warm start (when available) and preprocessing?

### ISSUE THREAD

**Issue by matteobarbieri** [slipguru/palladio#13]
This could solve the 'RangeScaler' issue and the fact that no warm-start strategy is implemented.

**Comment by fdtomasi** [comment]
I found a main issue of `sklearn` scikit-learn/scikit-learn#1674 
in which they discuss the possibility to add a warm-start strategy to GridSearchCV.

It doesn't seem to be clear on how structure a GridSearchCV with warm-start strategy, mainly because of how GridSearchCV is implemented, its parallel jobs and so on.

**Comment by fdtomasi** [comment]
See also this https://github.com/scikit-learn/scikit-learn/issues/1626
It is not clear on how to implement it.

I close this since this is not an issue of PALLADIO, which is independent on the estimator used.
